+ add cni mode zh blog
merbridge/website pull request #19
Opened 2022-05-18 10:09 UTC by kebe7jun

2022-05-18 10:09 UTC, kebe7jun commented
@merbridge/docs-maintainers PTAL.

2022-05-18 12:06 UTC, windsonsea requested changes
少量文字改动，让语句通顺一点

2022-05-18 12:06 UTC, windsonsea commented on content/zh/blog/2022/cni-mode/index.md
> +Merbridge CNI 模式的出现，旨在能够更好的适配服务网格的功能，在之前（没有 CNI 模式），Merbridge 能够做的事情比较有限，其中最大问题，就是不能适配注入 Istio 的 Sidecar Annotation，这就导致 Merbridge 无法排除某些端口或 IP 段的流量等。
Merbridge CNI 模式的出现，旨在能够更好地适配服务网格的功能。之前没有 CNI 模式时，Merbridge 能够做得事情比较有限。其中最大的问题是不能适配注入 Istio 的 Sidecar Annotation，这就导致 Merbridge 无法排除某些端口或 IP 段的流量等。

2022-05-18 12:06 UTC, windsonsea commented on content/zh/blog/2022/cni-mode/index.md
> +为此，我们设计了一套方法，其和 CNI 配合，完成获取当前 Pod 的 IP 的工作，以实现适配针对 Pod 的特殊配置。
为此，我们设计了一套方法，与 CNI 配合，能够获取当前 Pod 的 IP，以适配针对 Pod 的特殊配置。

2022-05-18 12:06 UTC, windsonsea commented on content/zh/blog/2022/cni-mode/index.md
> +其二，在之前的 Merbridge 版本中，我们只有 connect 处理主机发起请求的情况，这在同一台主机上的 Pod 互相通讯时，是没有问题的。但是当我们在不同主机之间通讯时，就会出现问题，因为按照之前的逻辑，在跨节点通讯时，流量不会被修改，导致在接收端还是需要 iptables 才能接收到。
其二，在之前的 Merbridge 版本中，只有 connect 会处理主机发起的请求，这在同一台主机上的 Pod 互相通讯时，是没有问题的。但是在不同主机之间通讯时就会出现问题，因为按照之前的逻辑，在跨节点通讯时流量不会被修改，这会导致在接收端还是离不开 iptables。

2022-05-18 12:06 UTC, windsonsea commented on content/zh/blog/2022/cni-mode/index.md
> +同时，我们还使用 Pod 优化了之前为了解决四元组冲突的方案，改为使用 bpf_bind 绑定源 IP，目的 IP 直接使用 `127.0.0.1`，为了后续支持 IPv6 做准备。
同时，我们还使用 Pod 优化了之前解决四元组冲突的方案，改为使用 bpf_bind 绑定源 IP，且目的 IP 直接使用 `127.0.0.1`，为后续支持 IPv6 做好准备。

2022-05-18 12:06 UTC, windsonsea commented on content/zh/blog/2022/cni-mode/index.md
> +我们同时考虑到可能存在主机直接访问 Pod 的情况，也为了影响范围更小，所以我们选择将 XDP 程序附加到 Pod 的网卡上，所以我们需要借助 CNI 的能力，在 Pod 创建时进行操作。
同时考虑到可能存在主机直接访问 Pod 的情况，也为了减小影响范围，我们选择将 XDP 程序附加到 Pod 的网卡上。这就需要借助 CNI 的能力，在创建 Pod 时进行附加操作。

2022-05-18 12:06 UTC, windsonsea commented on content/zh/blog/2022/cni-mode/index.md
> +为了保证 CNI 模式的正常运行，我们默认关闭 hardware-checksum 能力，这可能会影响到网络性能，建议大家在开启 CNI 模式前，先确认主机是否可开启 hardware-checksum 能力，如果有，建议设置 `--hardware-checksum=true` 已获得最佳的性能表现。
为了保证 CNI 模式的正常运行，我们默认关闭了 hardware-checksum 能力，这可能会影响到网络性能。建议大家在开启 CNI 模式前，先确认主机是否可开启 hardware-checksum 能力。如果可以开启，建议设置 `--hardware-checksum=true` 以获得最佳的性能表现。

2022-05-18 12:06 UTC, windsonsea commented on content/zh/blog/2022/cni-mode/index.md
> +测试方法，`ethtool -k <网卡> | grep tx-checksum-ipv4` 为 on 表示开启。
测试方法：`ethtool -k <网卡> | grep tx-checksum-ipv4` 为 on 时表示开启。

2022-05-19 02:39 UTC, windsonsea commented
/lgtm

2022-05-19 02:59 UTC, merged